//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common360.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common360.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SET IDENTITY_INSERT Provinces on;
        ///
        ///INSERT INTO Provinces (ProvinceId, Name) 
        ///VALUES (1,&apos;Azua&apos;),(2,&apos;Bahoruco&apos;),(3,&apos;Barahona&apos;),(4,&apos;Dajabón&apos;),
        ///	   (5,&apos;Distrito Nacional&apos;),(6,&apos;Duarte&apos;),(7,&apos;Elías Piña&apos;),
        ///	   (8,&apos;El Seibo&apos;),(9,&apos;Espaillat&apos;),(10,&apos;Hato Mayor&apos;),
        ///	   (11,&apos;Hermanas Mirabal&apos;),(12,&apos;Independencia&apos;),(13,&apos;La Altagracia&apos;),
        ///	   (14,&apos;La Romana&apos;),(15,&apos;La Vega&apos;),(16,&apos;María Trinidad Sánchez&apos;),
        ///	   (17,&apos;Monseñor Nouel&apos;),(18,&apos;Monte Cristi&apos;),(19,&apos;Monte Plata&apos;),
        ///	   (20,&apos;Pedernales&apos;),(21,&apos;Peravia&apos;),(22,&apos;Pu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProvincesData {
            get {
                return ResourceManager.GetString("ProvincesData", resourceCulture);
            }
        }
    }
}
